name: CI
on:
  push:
    branches: [main]
    paths-ignore:
      - 'wit-0.3.0-draft/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'wit-0.3.0-draft/**'

jobs:
  abi-up-to-date:
    name: Check ABI files are up-to-date
    runs-on: ubuntu-latest
    steps:
    # v4.2.2
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: WebAssembly/wit-abi-up-to-date@v24
      with:
        wit-bindgen: '0.37.0'
        all-features: 'true'
